START TRANSACTION;

CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(100),
    eMail VARCHAR(255) UNIQUE
) ENGINE=InnoDB;


COMMIT;