START TRANSACTION;

CREATE TABLE IF NOT EXISTS PlattformNutzerkonto (
    id INT AUTO_INCREMENT PRIMARY KEY,
    benutzername VARCHAR(255) NOT NULL,
    passwort VARCHAR(255) NOT NULL,
    rolle VARCHAR(100),
    eMail VARCHAR(255) UNIQUE
) ENGINE=InnoDB;

COMMIT;