START TRANSACTION;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(100),
    eMail VARCHAR(255) UNIQUE
    address VARCHAR(255),
    zipCode VARCHAR(10),
    city VARCHAR(100),
    country VARCHAR(100),
    phoneNumber VARCHAR(20),
    createdUser VARCHAR(255),
    createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modifiedUser VARCHAR(255),
    modifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    lastLogin TIMESTAMP,
    lastLoginIP VARCHAR(45),
) ENGINE=InnoDB;


COMMIT;